apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-skripsi-oryzasa-site
  namespace: istio-system
  labels:
    environment: development
spec:
  secretName: wildcard-skripsi-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.skripsi.oryzasa.site"
    - "skripsi.oryzasa.site"
  # Reflector annotations to mirror TLS secret to other namespaces
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "argocd,default,openbao"
