resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
logLevel: INFO
csi:
  enableCSIHostNetwork: true
  enableCephfsDriver: false
  enableRbdDriver: true
  enableSnat: true
