name: crapi
project: devsecops-skripsi
namespace: crapi
sync:
  automated: true
  prune: false
  selfHeal: true
  createNamespace: true
labels:
  app.kubernetes.io/part-of: infrastructure
  app.kubernetes.io/component: crapi
sources:
  - repoURL: oci://ghcr.io/valdo766hi/crapi-helm
    chart: crapi
    targetRevision: 0.1.5-rc0
    helm:
      releaseName: crapi
      valueFiles:
        - $values/deploy/manifests/crapi/values/values.yaml
  - repoURL: git@github.com:valdo766hi/devsecops-cicd-ssdf-slsa-evaluation.git
    targetRevision: HEAD
    ref: values
  - repoURL: git@github.com:valdo766hi/devsecops-cicd-ssdf-slsa-evaluation.git
    targetRevision: HEAD
    path: deploy/manifests/crapi
