apiVersion: v1
kind: Service
metadata:
  name: crapi-web
  namespace: crapi
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: crapi-web
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-web-ingress
  namespace: crapi
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8025
      targetPort: 8025
      protocol: TCP
  selector:
    app: mailhog
