apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # AppProject must be first
  - projects/devsecops-skripsi.yaml
  # Applications
  - applications/gateway-api.yaml
  - applications/argocd.yaml
