name: kyverno
project: devsecops-skripsi
namespace: kyverno
sync:
  automated: true
  prune: true
  selfHeal: true
  createNamespace: true
labels:
  app.kubernetes.io/part-of: infrastructure
  app.kubernetes.io/component: kyverno
sources:
  - repoURL: oci://ghcr.io/kyverno/charts/kyverno
    chart: kyverno
    targetRevision: 3.7.0
    helm:
      valueFiles:
        - $values/deploy/manifests/kyverno/values/values.yaml
  - repoURL: git@github.com:valdo766hi/devsecops-cicd-ssdf-slsa-evaluation.git
    targetRevision: HEAD
    ref: values
ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /metadata/annotations
      - /metadata/labels
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
      - /metadata/annotations
      - /metadata/labels
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
      - /metadata/annotations
      - /metadata/labels
