name: istio
project: devsecops-skripsi
namespace: istio-system
sync:
  automated: true
  prune: true
  selfHeal: true
  createNamespace: true
labels:
  app.kubernetes.io/part-of: infrastructure
  app.kubernetes.io/component: istio
ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istio-validator-istio-system
    jsonPointers:
      - /webhooks/0/failurePolicy
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
    jsonPointers:
      - /webhooks/0/failurePolicy
sources:
  - repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: 1.28.3
    helm:
      releaseName: istio-base
  - repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.28.3
    helm:
      releaseName: istiod
      valueFiles:
        - $values/deploy/manifests/istio/istiod/values/values.yaml
  - repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.28.3
    helm:
      releaseName: istio-gateway
      valueFiles:
        - $values/deploy/manifests/istio/gateway/values/values.yaml
  - repoURL: git@github.com:valdo766hi/devsecops-cicd-ssdf-slsa-evaluation.git
    targetRevision: HEAD
    ref: values
  - repoURL: git@github.com:valdo766hi/devsecops-cicd-ssdf-slsa-evaluation.git
    targetRevision: HEAD
    path: deploy/manifests/istio
