apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
  annotations:
    networking.istio.io/service-type: "NodePort"
    networking.istio.io/service-nodePort.http: "30080"
  labels:
    app: istio-gateway
    environment: development
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.skripsi.oryzasa.site"
      allowedRoutes:
        namespaces:
          from: All
