name: namespaces
project: devsecops-skripsi
namespace: default
sync:
  automated: true
  prune: true
  selfHeal: true
  createNamespace: false
labels:
  app.kubernetes.io/part-of: infrastructure
  app.kubernetes.io/component: namespaces
sources:
  - repoURL: git@github.com:valdo766hi/devsecops-cicd-ssdf-slsa-evaluation.git
    targetRevision: HEAD
    path: deploy/manifests/namespaces
