apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - istio-system.yaml
  - cert-manager.yaml
  - rook-ceph.yaml
  - openbao.yaml
  - external-secrets.yaml
  - trivy-system.yaml
