name: external-secrets
project: devsecops-skripsi
namespace: external-secrets
sync:
  automated: true
  prune: false
  selfHeal: true
  createNamespace: true
labels:
  app.kubernetes.io/part-of: infrastructure
  app.kubernetes.io/component: external-secrets
sources:
  - repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 1.3.1
    helm:
      valueFiles:
        - $values/deploy/manifests/external-secrets/values/values.yaml
  - repoURL: git@github.com:valdo766hi/devsecops-cicd-ssdf-slsa-evaluation.git
    targetRevision: HEAD
    ref: values
  - repoURL: git@github.com:valdo766hi/devsecops-cicd-ssdf-slsa-evaluation.git
    targetRevision: HEAD
    path: deploy/manifests/external-secrets
