apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: skripsi-openbao-store
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "skripsi-role"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
