apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-external-secret
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: skripsi-openbao-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: skripsi-testing-secret
  data:
    - secretKey: username
      remoteRef:
        key: "testing"
        property: "username"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
