name: reflector
project: devsecops-skripsi
namespace: kube-system
sync:
  automated: true
  prune: false
  selfHeal: true
  createNamespace: false
labels:
  app.kubernetes.io/part-of: infrastructure
  app.kubernetes.io/component: reflector
sources:
  - repoURL: oci://ghcr.io/emberstack/helm-charts/reflector
    chart: reflector
    targetRevision: 7.1.288
    helm:
      valueFiles:
        - $values/deploy/manifests/reflector/values/values.yaml
  - repoURL: git@github.com:valdo766hi/devsecops-cicd-ssdf-slsa-evaluation.git
    targetRevision: HEAD
    ref: values
